language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache: 
  npm: true
  directories:
    - ~/.cache

before_script:
  - npm ci

script: 
  - $(npm bin)/cypress run --record
  - bash build.sh