// Generated by dts-bundle v0.7.3

interface ISubscriber {
        off(): void;
        on(): void;
}
/**
    *
    *
    * @export
    * @class Raxy
    * @template S
    */
export default class Raxy<S> {
        state: S;
        constructor(store: S);
        /**
            *
            *
            * @memberof Raxy
            */
        connect: <P = any>(component: import("react").ComponentClass<{}, any>, mapper: (state: S) => Partial<P>) => import("react").ComponentClass<Partial<P>, any>;
        /**
            *
            *
            * @memberof Raxy
            */
        subscribe: <P>(callback: any, mapper: (state: S) => P) => ISubscriber;
}
export {};

